### ISSUE TITLE
Can't post to

### ISSUE THREAD

**Issue by sasharh1** [harperreed/node-ifttt-mqtt-bridge#2]
Thanks for this. Unfortunately I have not yet been able to get it to work. I followed your instructions as given, but when I go to test it using curl, I get this error (from the logs):

TypeError: Cannot read property 'api_key' of undefined
    at exports.post.functions.https.onRequest (/user_code/index.js:24:32)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/providers/https.js:57:9)
    at /var/tmp/worker/worker.js:762:7
    at /var/tmp/worker/worker.js:745:11
    at _combinedTickCallback 

The only thing I've changed in your code is the config vars:

firebase functions:config:set mqtt.server.port=16754
  firebase functions:config:set mqtt.server.host=mqtt://m24.cloudmqtt.com
  firebase functions:config:set mqtt.server.user=vsnsleot
  firebase functions:config:set mqtt.server.password=<the password here>
  firebase functions:config:set access.api_key=<the key here>

The API key is the one from the 'project settings' page on firebase, right?

The CURL request I'm using is:  curl https://us-central1-htptomtp.cloudfunctions.net/post -d "topic=IFTTT/goodnight" -d "message=on" -d "key=<the key here>"

Any help would be much appreciated!

**Comment by sasharh1** [comment]
Never mind - I stupidly thought you had to edit the config in index.js rather than in the CLI.
